name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.json'
      - '**.md'
      - keywords.txt
      - CI/**
      - '!CI/build/arduino-cli.py'
      - '!CI/build/platformio-builder.py'
      - '!CI/build/examples/**'
      - tools/**
      - '!tools/platformio-build.py'
  pull_request:
    paths-ignore:
      - '*.json'
      - '**.md'
      - keywords.txt
      - CI/**
      - '!CI/build/arduino-cli.py'
      - '!CI/build/platformio-builder.py'
      - '!CI/build/examples/**'
      - tools/**
      - '!tools/platformio-build.py'

# jobs:
#   astyle_check:
#     runs-on: ubuntu-latest
#     name: Astyle
#     steps:
#     - name: Checkout
#       uses: actions/checkout@master

#     - name: Astyle
#       id: Astyle
#       uses: OS-Q/ArduinoCore/check-style@master
#       with:
#         astyle-definition: 'CI/astyle/.astylerc'
#         ignore-path-list: 'CI/astyle/.astyleignore'

#     - name: Astyle Errors
#       if: failure()
#       run: |
#         cat ${{ steps.Astyle.outputs.astyle-result }}
#         exit 1

#   check_build:
#     runs-on: ubuntu-latest
#     name: Check
#     steps:
#     - name: Checkout
#       uses: actions/checkout@master

#     - name: Compilation
#       id: Compile
#       uses: OS-Q/ArduinoCore/check-build@master
#       with:
#         additional-url: 'https://github.com/OS-Q/ArduinoCore/releases/latest/download/package_stm_index.json'

#     - name: Errors
#       if: failure()
#       run: |
#         cat ${{ steps.Compile.outputs.compile-result }}
#         exit 1

#   action_build:
#     runs-on: ubuntu-latest
#     name: Action
#     steps:
#     - name: Checkout
#       uses: actions/checkout@master
#       with:
#         submodules: "recursive"

#     - name: Compile
#       uses: OS-Q/ArduinoCore@master
#       with:
#         board: "blackpill_f103c8"

#   tests_build:
#     name: Tests
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           submodules: "recursive"
#           fetch-depth: 1

#       - name: Set up Python
#         uses: actions/setup-python@v1
#         with:
#           python: 3.9

#       - name: Install
#         run: |
#           python -m pip install --upgrade pip
#           pip install -U https://github.com/OS-Q/S03/releases/latest/download/S03.zip
#           pio platform install https://github.com/OS-Q/P21/releases/latest/download/P21.zip

#       - name: Build
#         run: |
#           pio run -d tests/blink
